#ifndef HEADFILE_H
#define HEADFILE_H
#include <QMainWindow>
#include <QPushButton>
#include <QLabel>
#include <QLineEdit>
#include <QTextEdit>
#include <QFont>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QMessageBox>
#include <QDialog>
#include <QTableWidget>
#include <QHeaderView>
#include <QAbstractItemView>
#include <QDebug>
#include <QIcon>
#include <QPalette>
#include <QPaintEvent>
#include <QComboBox>
#include <QSpinBox>
#include <QCommandLinkButton>
#include <QButtonGroup>
#include <QSqlTableModel>
#include <QSqlError>
#include <QSqlQuery>
#include <QVariant>
#include "maindata.h"

#endif // HEADFILE_H
